version: '3.4'

services:
  tests_sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tests_sqlserver
    ports:
      - 1436:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssword11!!
